### PR TITLE
(GH-412) Implement ConnectionHandler

### LINKED ISSUE #412: Refactor ConnectionManager
**As a** developer

**I would like to** simplify the connection logic for stdio and tcp language server connections

**so that I** don't have to rework or edit large swaths of code to add new features

### PR DESCRIPTION
**Pull request by jpogran**
This PR replaces the `ConnectionManager` class with a new set of `ConnectionHandler` implementations that separate and isolate protocol specific code to concrete classes instead of a monolith spaghetti code monster.

- [x] Expose `OutputChannel` for external to `OutpuChannelLogger` use
- [x] Implement `ConnectionHandler` base
- [x] Implement `StdioConnectionHandler`
- [x] Implement `TcpConnectionHandler`
- [x] Modify `extension.ts` to use the new connection handlers
- [x] Removes `ConnectionManager` and `PuppetLanguageClient`

This also includes several maintenance commits that resolve minor issues:

- [x] Removes `docs` folder from packaging to reduce `VSIX` size
- [x] Improve workspace settings to exclude `node_modules`
- [x] Cleanup commits

This closes #412

### CODE REVIEW

**Comment by jpogran** [comment]
### Manual Checklist osx 10.12.6

- [ ] Loads extension
  - [ ] Loads LangaugeServer
    - [ ] using PDK as source
    - [ ] using Puppet-Agent as source
    - [ ] using STDIO
    - using TCP
      - [ ] using local langserver
      - [ ] using remote langserver
  - Configuration
    - [ ] debugFilePath: Works fine, but a note - if you specify a log file path you don't have permissions to, the extension fails without a useful warning.
    - [ ] featureFlags: Not sure what I can test here, don't know of any feature flags
    - [ ] logLevel
    - [ ] protocol
    - [ ] tcp
      - [ ] address
      - [ ] port
    - [ ] timeout
    - [ ] format.enable
    - [ ] installDirectory
    - [ ] installType
  - Functionality
    - [ ] Syntax highlighting
    - [ ] Hover
    - [ ] Autocomplete
    - [ ] Outline View
    - [ ] Breadcrumbs
    - [ ] Go to Symbol
    - [ ] Linting (errors warning show in problems pane)
  - Features
    - [ ] Format document works (note some formatting not done by puppet-lint)
    - [ ] Node Graph works with example manifest
    - [ ] Puppet Resource user works
    - PDK (note these are shell execs so unlikely to break)
      - [ ] new module
      - [ ] new class
      - [ ] validate
      - [ ] test unit
  - [ ] Debug Adapter - Dumps out with "Operation Cancelled" - the JSON _seems_ valid (no syntax errors) - JSON and logs below.
    - *This can't be autoamted at the moment, and is experimental so is not part of our test run right now*
  - Command pallate
    - [ ] Restart Current Session - Always results in "Running the contributed command:'extension.puppetRestartSession' failed and sets the status bar to initialization complete (logs below) and then never does anything else.
    - [ ] Show Connection Logs
    - [ ] PDK New Module
    - [ ] PDK Test Unit
    - [ ] PDK Validate
    - [ ] PDK New Task
    - [ ] Puppet Resource
    - [ ] Open Node Graph to the Side
  - UI Button
    - [ ] PDK new module - I don't see a UI button with the locally installed VSIX?
  - Context Menu
    - [ ] PDK New Module
    - [ ] PDK Test Unit
    - [ ] PDK Validate
    - [ ] PDK New Task
    - [ ] Puppet Resource
    - [ ] Open Node Graph to the Side

**Comment by jpogran** [comment]
Issue #439 was created to address RestartSession command

**Comment by glennsarti** [comment]
@jpogran This looks concerning from Michael's logs

```
DEBUG: 2018-12-03T21:11:24.097Z [getRubyExecFromPuppetAgent] Using environment variable GEM_PATH=undefined
DEBUG: 2018-12-03T21:11:24.097Z [getRubyExecFromPuppetAgent] Using environment variable GEM_HOME=undefined
```

undefined?

**Comment by jpogran** [comment]
@glennsarti this happens because I consolidated the logging to one place outside of the method that builds the environment, but did not choose to log which environment variable depending on whether agent or pdk is used. So, we have the whole list, whether or not we use them, and in this case it was from an agent run, which doesn't use gem_home or gem_path.

I can either add a new switch statement and only output whichever is used like we used to, or log everything regardless of whether its used or not

**Comment by glennsarti** [comment]
Hrmmm debugging is working fine on both agent and pdk for me

**Pull request merged**
